services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: vkalance_app
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: vkalance_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    container_name: vkalance_mongoExpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    depends_on:
      - mongodb