FROM golang:1.23-alpine AS builder

ENV ACCESS_SECRET_KEY=secret
ENV SERVER_PORT=5000
ENV MONGO_URI=mongodb://admin:admin@mongodb:27017

WORKDIR /build

COPY go.* .

RUN go mod download && go mod tidy

COPY . .

RUN go install github.com/air-verse/air@latest

CMD ["air","-c",".air.toml"]